### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by 1am** [tessel/bglib#2]
Hi

I've tried using your bglib npm with the BLED device and I've ended up with the following script:

``` javascript
var bg = require('bglib');
var bglib = new bg()
bglib.setPacketMode(true);



var SerialPort = require("serialport").SerialPort
var serialPort = new SerialPort("/dev/tty.usbmodem1", {
  baudrate: 38400
});

serialPort.on("open", function(){
  console.log('open');

  serialPort.on('data', function(data) {
    console.log('data received: ' + data);

    bglib.parseIncoming(data, function(err, parsedPackets) {
      console.log("Parsed packets: ", parsedPackets);
    });

  });

  var p = bglib.getPacket(bg.api.connectionDisconnect, function(err, packet){
    console.log( "error", err );
    console.log( "packet" , packet , packet.getByteArray() )
  });
  console.log( "p" , p );  
});
```

I've got a few questions based on the script above:
1) Why is the getPacket an async function with a callback and doesn't return anything after calling? I don't really understand what's to gain from such approach as the packet creation doesn't need to connect to any remote devices, etc?
2) When I change the _bg.api.systemHello_ to _bg.api.connectionDisconnect_ the script fails with the following error: 

```
[Error: Invalid number of parameters passed for method]
```

I've changed it to the code paster below which made it work but how do I know which api function requires which parameters? I've seen the _paramCode_ attributes in _bglib.api_ variable but just by looking at it briefly I don't see what 0x222222 or 0x822 values mean exactly?

``` javascript
  var p = bglib.getPacket(bg.api.connectionDisconnect, [0], function(err, packet){
    console.log( "error", err );
    console.log( "packet" , packet , packet.getByteArray() )
  });

```

**Comment by andrewjaykeller** [comment]
@1am do you still have this script?
